Visitor can Register for an Account
CraftAcademy/classy_news_backend pull request #5
Opened 2019-10-26 15:05 UTC by beccaburns

Register for Account
===============

[PT-Link](https://www.pivotaltracker.com/story/show/169253742)

## PR Contents
- User model 
- FactoryBot for user
- Request specs for user
- Authentication & registration spec files
- Validations for user
- Devise Token Auth gem installed

## What we Learned
- Continued learning on how to write specs for unit testing API

2019-10-26 15:32 UTC, yasmineezequiel approved these changes

2019-10-28 09:15 UTC, yasmineezequiel approved these changes

2019-10-28 15:51 UTC, shsteindorsson approved these changes

2019-10-28 15:51 UTC, shsteindorsson commented on spec/models/user_spec.rb
> +    #it { is_expected.to validate_presence_of(:nickname) }
Can we remove the commented line?

2019-10-29 06:59 UTC, faraznaeem requested changes

2019-10-29 06:59 UTC, faraznaeem commented on index_users_on_city
> +      create    db/migrate/20191026153252_add_index_column_to_user.rb
What is this?

2019-10-29 06:59 UTC, faraznaeem commented on spec/requests/api/v1/registrations_spec.rb
> +      FactoryBot.create(:user, nickname: 'becca',
Do you need to write `FactoryBot.create`?

2019-10-29 12:34 UTC, shsteindorsson approved these changes

2019-10-29 12:41 UTC, lucamarial approved these changes

2019-10-29 12:44 UTC, DavveDavve commented on spec/support/response_json.rb
> +end
Why does this show here, when in the code it is included in the rails_helper instead of response_json?

2019-10-29 12:45 UTC, DIzosimov approved these changes

2019-10-29 13:58 UTC, faraznaeem approved these changes

2019-10-29 13:58 UTC, merged